
mybatis-plus:
  mapper-location: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://yun2:3306/vandesr
      username: root
      password: code4fun1234
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://yun2:3306/vandesr
      username: root   # 只读账户
      password: code4fun1234
      driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: yun2
#    database: 0
#    password: code4fun12345678
#    jedis:
#      pool:
#        min-idle: 0
#        max-active: 8
#    timeout: 5000
#    sentinel:
#      master: mymaster
#      nodes: yun2:27001
  application:
    name: vandesr-admin
  kafka:
    consumer:
      group-id: test01
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: latest
    bootstrap-servers: yun2:9092
    listener:
      concurrency: 10
    producer:
      bootstrap-servers:  yun2:9092
      retries: 1
      batch-size: 40960
      buffer-memory: 40960

server:
  port: 8088
logging:
  level:
    root: info
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/
